Repository Unirep/Unirep, pull requests merged in 2023-04, with the labels that each got.

#377 feat(utils): use `@semaphore-protocol/identity`
  packages/circuits/package.json
  packages/circuits/test/epochKeyLite.test.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/circuits/test/verifyEpochKey.test.ts
  packages/contracts/README.md
  packages/contracts/package.json
  packages/contracts/test/accessors.test.ts
  packages/contracts/test/userSignup.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/contracts/test/verifier.test.ts
  packages/core/README.md
  packages/core/package.json
  packages/core/src/UserState.ts
  packages/core/test/attestation.test.ts
  packages/core/test/epochKeyLite.test.ts
  packages/core/test/epochKeyProof.test.ts
  packages/core/test/epochTree.test.ts
  packages/core/test/reputationProof.test.ts
  packages/core/test/stateTree.test.ts
  packages/core/test/synchronizer.test.ts
  packages/core/test/test.ts
  packages/core/test/userSignup.test.ts
  packages/core/test/userState.test.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/utils-api/identity.md
  packages/docs/docs/utils-api/types.md
  packages/docs/sidebars.js
  packages/test/src/index.ts
  packages/utils/README.md
  packages/utils/src/identity.ts
  packages/utils/src/index.ts
  packages/utils/src/snark.ts
  packages/utils/test/ZkIdentity.test.ts
  yarn.lock
Labels: dependencies, ready for review

#376 fix(contracts): prevent epoch key 0 and 1 to be attested
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/test/attestation.test.ts
  packages/core/test/attestation.test.ts
  packages/core/test/synchronizerAttesters.test.ts
  packages/docs/docs/contracts-api/errors.md
Labels: bug, ready for review, vulnerability

#388 fix(ci): run contracts tests in parallel when possible
  .circleci/config.yml
  packages/contracts/package.json
Labels: ready for review

#382 Reveal all epk
  packages/circuits/circuits/buildOrderedTree.circom
  packages/circuits/circuits/epochKey.circom
  packages/circuits/circuits/leafHasher.circom
  packages/circuits/circuits/proveReputation.circom
  packages/circuits/circuits/signup.circom
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/BuildOrderedTree.ts
  packages/circuits/src/CircuitConfig.ts
  packages/circuits/src/UserStateTransitionProof.ts
  packages/circuits/src/circuits.ts
  packages/circuits/src/index.ts
  packages/circuits/test/buildOrderedTree.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/contracts/libraries/Polysum.sol
  packages/contracts/contracts/libraries/ReusableMerkleTree.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/attesterSignup.test.ts
  packages/contracts/test/epoch.test.ts
  packages/contracts/test/epochSealing.test.ts
  packages/contracts/test/userSignup.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/contracts/test/verifier.test.ts
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/test/attestation.test.ts
  packages/core/test/epochTree.test.ts
  packages/core/test/sealEpoch.test.ts
  packages/core/test/stateTree.test.ts
  packages/core/test/synchronizer.test.ts
  packages/core/test/test.ts
  packages/core/test/userState.test.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/circuits-api/build-ordered-tree.md
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/circuits-api/user-state-transition-proof.md
  packages/docs/docs/contracts-api/errors.md
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/docs/core-api/synchronizer.md
  packages/docs/docs/protocol/attestation.md
  packages/docs/docs/protocol/nullifiers.md
  packages/docs/docs/protocol/polysum.md
  packages/docs/docs/protocol/trees.md
  packages/docs/docs/protocol/user-state-transition.md
  packages/docs/docs/utils-api/constants.md
  packages/docs/docs/utils-api/hashes.md
  packages/docs/sidebars.js
  packages/test/src/index.ts
  packages/utils/src/crypto.ts
Labels: ready for review

#395 refactor: remove EPOCH_TREE_ARITY config option
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/CircuitConfig.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/config.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/core/src/Synchronizer.ts
  packages/docs/docs/contracts-api/unirep-sol.md
Labels: ready for review

#394 chore(contracts): revert with error
  packages/contracts/contracts/Unirep.sol
Labels: ready for review

#391 chore(circuits): remove unused circuits
  packages/circuits/circuits/exists.circom
  packages/circuits/circuits/inclusionNoninclusion.circom
  packages/circuits/circuits/proveReputation.circom
  packages/circuits/circuits/sparseMerkleTree.circom
Labels: ready for review

#390 fix(circuits): don't allow inclusion proof for 0 leaf
  packages/circuits/circuits/incrementalMerkleTree.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/test/incrementalMerkleTree.test.ts
Labels: ready for review

#386 Add history tree
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/CircuitConfig.ts
  packages/circuits/src/UserStateTransitionProof.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/src/schema.ts
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/circuits-api/user-state-transition-proof.md
  packages/docs/docs/contracts-api/errors.md
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/docs/core-api/schema.md
  packages/docs/docs/core-api/synchronizer.md
  packages/docs/docs/protocol/trees.md
Labels: ready for review

#367 Multi attesters
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/src/schema.ts
  packages/core/test/attestation.test.ts
  packages/core/test/synchronizer.test.ts
  packages/core/test/synchronizerAttesters.test.ts
  packages/core/test/userState.test.ts
  packages/core/test/utils.ts
  packages/docs/docs/core-api/synchronizer.md
  packages/docs/docs/core-api/user-state.md
Labels: ready for review

#399 fix(core): get data nullifier logic
  packages/core/src/UserState.ts
Labels: ready for review

#400 Combined repl field
  packages/circuits/circuits/bigComparators.circom
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/CircuitConfig.ts
  packages/circuits/test/bigComparators.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/epoch.test.ts
  packages/contracts/test/userSignup.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/src/schema.ts
  packages/core/test/attestation.test.ts
  packages/core/test/stateTree.test.ts
  packages/core/test/synchronizer.test.ts
  packages/core/test/userSignup.test.ts
  packages/core/test/userState.test.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/docs/core-api/schema.md
  packages/docs/docs/protocol/data.md
  packages/docs/docs/protocol/epoch-key.md
  packages/docs/docs/protocol/trees.md
  packages/docs/docs/protocol/user-state-transition.md
  packages/docs/docs/protocol/users-and-attesters.md
  packages/docs/docs/utils-api/constants.md
  packages/docs/docs/welcome.md
  packages/docs/sidebars.js
  packages/utils/src/crypto.ts
Labels: ready for review

#408 chore: bump poseidon-lite to 0.1.1
  packages/circuits/test/bigComparators.test.ts
  packages/circuits/test/preventDoubleAction.test.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/core/src/UserState.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/protocol/epoch-key.md
  packages/docs/docs/utils-api/hashes.md
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/IncrementalMerkleTree.ts
  packages/utils/src/SparseMerkleTree.ts
  packages/utils/src/crypto.ts
  packages/utils/test/SparseMerkleTree.test.ts
  packages/utils/test/crypto.test.ts
  yarn.lock
Labels: ready for review

#410 refactor(circuits): switch BigNumberish -> bigint, remove ethers dep
  packages/circuits/package.json
  packages/circuits/src/BaseProof.ts
  packages/circuits/src/EpochKeyLiteProof.ts
  packages/circuits/src/EpochKeyProof.ts
  packages/circuits/src/PreventDoubleActionProof.ts
  packages/circuits/src/ReputationProof.ts
  packages/circuits/src/SignupProof.ts
  packages/circuits/src/UserStateTransitionProof.ts
  packages/circuits/src/circuits.ts
  packages/circuits/test/epochKeyLite.test.ts
  packages/circuits/test/preventDoubleAction.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/core/src/Synchronizer.ts
  packages/docs/docs/circuits-api/base-proof.md
  packages/docs/docs/circuits-api/network-prover.md
  yarn.lock
Labels: ready for review

#413 chore(contracts): remove unused openzeppelin imports
  packages/contracts/contracts/Unirep.sol
Labels: ready for review

#414 refactor(circuits): remove root level config folder
  packages/circuits/config/index.ts
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/index.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/attesterSignup.test.ts
  packages/contracts/test/config.test.ts
  packages/contracts/test/epoch.test.ts
  packages/contracts/test/userSignup.test.ts
  packages/contracts/test/userStateTransition.test.ts
  packages/contracts/test/verifier.test.ts
  packages/test/src/index.ts
Labels: ready for review

#412 refactor: change epoch key/state tree leaf structure
  packages/circuits/circuits/epochKeyLite.circom
  packages/circuits/circuits/leafHasher.circom
  packages/circuits/circuits/preventDoubleAction.circom
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/test/userStateTransition.test.ts
  packages/docs/docs/protocol/epoch-key.md
  packages/docs/docs/protocol/trees.md
  packages/utils/src/crypto.ts
Labels: ready for review

#421 chore(contracts): bump poseidon-solidity version
  packages/contracts/package.json
  yarn.lock
Labels: ready for review

#422 Fix rep circuits
  packages/circuits/circuits/bigComparators.circom
  packages/circuits/circuits/proveReputation.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/ReputationProof.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/verifier.test.ts
  packages/core/src/UserState.ts
  packages/core/test/reputationProof.test.ts
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/circuits-api/reputation-proof.md
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/docs/core-api/user-state.md
Labels: bug, ready for review

#424 chore(contracts): bump poseidon-solidity version
  packages/contracts/deploy/deploy.ts
  packages/contracts/package.json
  yarn.lock
Labels: ready for review
