Repository Unirep/Unirep, pull requests merged in 2023-06, with the labels that each got.

#477 feat(core): containerize the class with getters
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/test/synchronizer.test.ts
  packages/core/test/synchronizerAttesters.test.ts
  packages/core/test/utils.ts
  packages/docs/docs/core-api/synchronizer.md
  packages/docs/docs/core-api/user-state.md
Labels: ready for review, vulnerability

#476 471 rename proof verifiers
  packages/contracts/contracts/verifierHelpers/BaseVerifierHelper.sol
  packages/contracts/contracts/verifierHelpers/EpochKeyLiteVerifierHelper.sol
  packages/contracts/contracts/verifierHelpers/EpochKeyVerifierHelper.sol
  packages/contracts/contracts/verifierHelpers/ReputationVerifierHelper.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/verifier.test.ts
  packages/core/test/synchronizerAttesters.test.ts
  packages/docs/docs/contracts-api/base-verifier-helper.md
  packages/docs/docs/contracts-api/epoch-key-lite-verifier-helper.md
  packages/docs/docs/contracts-api/epoch-key-verifier-helper.md
  packages/docs/docs/contracts-api/errors.md
  packages/docs/docs/contracts-api/iverifier-sol.md
  packages/docs/docs/contracts-api/reputation-verifier-helper.md
  packages/docs/sidebars.js
Labels: documentation, ready for review

#464 Fix manual signup
  packages/circuits/circuits/leafHasher.circom
  packages/circuits/circuits/signup.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/SignupProof.ts
  packages/circuits/test/signup.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/test/userSignup.test.ts
  packages/core/test/userSignup.test.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/circuits-api/signup-proof.md
  packages/docs/docs/protocol/trees.md
  packages/docs/docs/utils-api/hashes.md
  packages/utils/src/crypto.ts
Labels: ready for review

#478 fix(core): prevent running setup twice
  packages/core/src/Synchronizer.ts
Labels: enhancement, ready for review

#441 Get started
  packages/docs/docs/getting-started/create-unirep-app.mdx
  packages/docs/docs/getting-started/ts-js.md
  packages/docs/docusaurus.config.js
  packages/docs/package.json
  packages/docs/sidebars.js
  packages/docs/src/pages/index.module.css
  packages/docs/static/img/create-unirep-app/architecture.png
  packages/docs/static/img/create-unirep-app/dashboard.png
  packages/docs/static/img/create-unirep-app/join.png
  packages/docs/static/img/create-unirep-app/prove_data.png
  packages/docs/static/img/create-unirep-app/request_data.png
  packages/docs/static/img/create-unirep-app/ust.png
  yarn.lock
Labels: documentation

#449 fix: store replacement field in 253 bits to avoid alias check
  packages/circuits/circuits/bigComparators.circom
  packages/circuits/circuits/epochKeyLite.circom
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/src/CircuitConfig.ts
  packages/circuits/src/EpochKeyLiteProof.ts
  packages/circuits/src/EpochKeyProof.ts
  packages/circuits/src/PreventDoubleActionProof.ts
  packages/circuits/src/ReputationProof.ts
  packages/circuits/src/SignupProof.ts
  packages/circuits/test/bigComparators.test.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/utils.ts
  packages/contracts/abi/Unirep.json
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/contracts/verifierHelpers/BaseVerifierHelper.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/attestation.test.ts
  packages/contracts/test/attestationMax.test.ts
  packages/contracts/test/userSignup.test.ts
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
  packages/core/test/reputationProof.test.ts
  packages/core/test/userSignup.test.ts
  packages/core/test/userStateTransition.test.ts
  packages/docs/docs/protocol/data.md
Labels: ready for review

#482 doc: add warning for publishing overall reputation
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/core-api/user-state.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/circuits-api/circuits.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/core-api/user-state.md
Labels: documentation, ready for review, vulnerability

#484 doc: add getting started 2.0.0-beta-3
  packages/docs/versioned_docs/version-2.0.0-beta-3/getting-started/create-unirep-app.mdx
  packages/docs/versioned_docs/version-2.0.0-beta-3/getting-started/ts-js.md
  packages/docs/versioned_sidebars/version-2.0.0-beta-3-sidebars.json
Labels: documentation, ready for review

#483 doc: warn potential attestation loss
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/contracts-api/unirep-sol.md
Labels: documentation, ready for review, vulnerability

#489 refactor(core): remove corner cases
  packages/core/src/UserState.ts
Labels: ready for review

#485 Fix attest order
  packages/contracts/deploy/deploy.ts
  packages/core/src/UserState.ts
  packages/core/test/userState.test.ts
  packages/docs/docs/core-api/user-state.md
Labels: ready for review, vulnerability

#486 Fix logic
  packages/core/src/Synchronizer.ts
  packages/core/src/UserState.ts
Labels: ready for review

#490 fix(circuits): constrain shifted bit values
  packages/circuits/circuits/bigComparators.circom
  packages/circuits/circuits/userStateTransition.circom
Labels: ready for review

#497 chore(circuits): remove unused circuits
  packages/circuits/circuits/bigComparators.circom
  packages/circuits/circuits/epochKey.circom
  packages/circuits/circuits/epochKeyLite.circom
  packages/circuits/circuits/hasher.circom
  packages/circuits/circuits/modulo.circom
  packages/circuits/circuits/preventDoubleAction.circom
  packages/circuits/circuits/proveReputation.circom
  packages/circuits/circuits/signup.circom
  packages/circuits/circuits/userStateTransition.circom
  packages/circuits/scripts/circuits.mjs
  packages/circuits/test/bigComparators.test.ts
Labels: ready for review
