Repository Unirep/Unirep, pull requests merged in 2023-05, with the labels that each got.

#435 doc: add explorer link and feedback link
  packages/docs/docs/welcome.md
  packages/docs/docusaurus.config.js
  packages/docs/src/css/custom.css
  packages/docs/versioned_docs/version-2.0.0-beta-3/welcome.md
Labels: documentation, ready for review

#429 fix(circuits): add template variable assertions
  packages/circuits/circuits/incrementalMerkleTree.circom
  packages/circuits/circuits/proveReputation.circom
  packages/circuits/circuits/userStateTransition.circom
Labels: ready for review, vulnerability

#436 test(core): mirep and maxrep test
  packages/core/test/reputationProof.test.ts
Labels: test, ready for review

#432 doc: update package readme files
  README.md
  packages/circuits/README.md
  packages/contracts/README.md
  packages/core/README.md
  packages/utils/README.md
Labels: documentation, ready for review

#440 doc: update pull request template
  .github/pull_request_template.md
Labels: documentation, ready for review

#439 feat(circuits): export web prover, add tests
  packages/circuits/package.json
  packages/circuits/provers/web.ts
  packages/circuits/test/provers.test.ts
  packages/docs/docs/circuits-api/network-prover.md
  packages/docs/docs/circuits-api/prover.md
  packages/docs/docs/circuits-api/web-prover.mdx
  packages/docs/docs/testnet-deployment.mdx
  packages/docs/sidebars.js
  yarn.lock
Labels: ready for review

#431 User-Defined Data Schemas
  packages/core/src/DataSchema.ts
  packages/core/src/index.ts
  packages/core/test/dataSchema.test.ts
  packages/docs/docs/core-api/data-schema.md
  packages/docs/sidebars.js
Labels: enhancement

#443 Atomic build circuits
  packages/circuits/scripts/buildSnarks.mjs
  packages/circuits/scripts/downloadPtau.mjs
Labels: enhancement, ready for review

#446 refactor(contracts): remove DEPLOY_DELAY
  packages/contracts/deploy/deploy.ts
  packages/contracts/package.json
  packages/core/package.json
Labels: ready for review

#448 fix(circuits): atomic copy build files
  packages/circuits/scripts/buildSnarks.mjs
  packages/circuits/scripts/copyAtomic.mjs
  packages/circuits/scripts/downloadPtau.mjs
Labels: ready for review

#461 chore(ci): download pre-built circom in ci
  .circleci/config.yml
Labels: ready for review

#462 feat(core): register event handlers in synchronizer after constructor
  packages/core/src/Synchronizer.ts
Labels: ready for review

#458 chore(circuits): add dummy square to public inputs without constraints
  packages/circuits/circuits/epochKeyLite.circom
Labels: ready for review

#463 fix(contracts): should not include `@unirep/test` in contract dependencies
  packages/contracts/package.json
  yarn.lock
Labels: ready for review

#437 Doc intro
  packages/docs/docs/welcome.md
  packages/docs/docusaurus.config.js
  packages/docs/sidebars.js
  packages/docs/src/pages/index.js
  packages/docs/static/img/application.png
  packages/docs/static/img/description-image.svg
  packages/docs/static/img/unirep-banner.png
  packages/docs/static/img/unirep-doc.png
  packages/docs/static/img/unirep-icon.png
  packages/docs/static/img/user & attester flow.png
  packages/docs/versioned_docs/version-2.0.0-beta-3/welcome.md
  packages/docs/versioned_sidebars/version-2.0.0-beta-3-sidebars.json
Labels: documentation, ready for review

#468 chore(ci): change circom binary link
  .circleci/config.yml
Labels: ready for review

#459 fix(contracts): change EpochKeyData layout
  packages/circuits/src/CircuitConfig.ts
  packages/contracts/contracts/Unirep.sol
  packages/contracts/contracts/interfaces/IUnirep.sol
  packages/contracts/deploy/deploy.ts
  packages/contracts/test/config.test.ts
Labels: ready for review
