Repository Unirep/Unirep, pull requests merged in 2023-07, with the labels that each got.

#504 fix(core): fix handling history leaves
  packages/core/src/Synchronizer.ts
  packages/core/src/schema.ts
  packages/core/test/synchronizerAttesters.test.ts
Labels: bug, ready for review

#502 chore(circuits): update circuits config
  packages/circuits/scripts/buildSnarks.mjs
  packages/circuits/src/CircuitConfig.ts
Labels: ready for review

#506 Update utils packages and documentation
  packages/docs/docs/contracts-api/unirep-sol.md
  packages/docs/docs/contracts-api/verifiers/base-verifier-helper.md
  packages/docs/docs/getting-started/ts-js.md
  packages/docs/docs/protocol/data.md
  packages/docs/docs/utils-api/constants.md
  packages/docs/docs/utils-api/hashes.md
  packages/docs/docs/utils-api/helpers.md
  packages/docs/docs/utils-api/incremental-tree.md
  packages/docs/docs/utils-api/installation.md
  packages/docs/docs/utils-api/sparse-tree.md
  packages/docs/sidebars.js
  packages/docs/src/pages/index.module.css
  packages/docs/versioned_docs/version-2.0.0-beta-1/contracts-api/unirep-sol.md
  packages/docs/versioned_docs/version-2.0.0-beta-2/contracts-api/unirep-sol.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/contracts-api/unirep-sol.md
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/IncrementalMerkleTree.ts
  packages/utils/src/SparseMerkleTree.ts
  packages/utils/src/crypto.ts
  packages/utils/src/index.ts
  packages/utils/src/stringify.ts
  packages/utils/test/SparseMerkleTree.test.ts
  packages/utils/test/stringify.test.ts
  yarn.lock
Labels: documentation, ready for review

#507 Update circuits doc
  packages/circuits/README.md
  packages/circuits/test/incrementalMerkleTree.test.ts
  packages/circuits/test/preventDoubleAction.test.ts
  packages/circuits/test/proveReputation.test.ts
  packages/circuits/test/userStateTransition.test.ts
  packages/circuits/test/utils.ts
  packages/docs/docs/circuits-api/base-proof.md
  packages/docs/docs/circuits-api/circuit-config.md
  packages/docs/docs/circuits-api/circuits.md
  packages/docs/docs/circuits-api/epoch-key-proof.md
  packages/docs/docs/circuits-api/installation.md
  packages/docs/docs/circuits-api/reputation-proof.md
  packages/docs/docs/circuits-api/signup-proof.md
  packages/docs/docs/circuits-api/user-state-transition-proof.md
  packages/docs/docs/core-api/user-state.md
  packages/docs/docs/utils-api/types.md
  packages/docs/sidebars.js
  packages/docs/versioned_docs/version-2.0.0-alpha-2/contracts-api/base-proof.md
  packages/docs/versioned_docs/version-2.0.0-alpha-2/contracts-api/epoch-key-proof.md
  packages/docs/versioned_docs/version-2.0.0-alpha-2/protocol/attestation.md
  packages/docs/versioned_docs/version-2.0.0-alpha-2/utils-api/hashes.md
  packages/docs/versioned_docs/version-2.0.0-alpha-3/circuits-api/base-proof.md
  packages/docs/versioned_docs/version-2.0.0-alpha-3/circuits-api/circuits.md
  packages/docs/versioned_docs/version-2.0.0-alpha-3/circuits-api/epoch-key-proof.md
  packages/docs/versioned_docs/version-2.0.0-alpha-3/protocol/attestation.md
  packages/docs/versioned_docs/version-2.0.0-alpha-3/utils-api/hashes.md
  packages/docs/versioned_docs/version-2.0.0-beta-1/circuits-api/base-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-1/circuits-api/circuits.md
  packages/docs/versioned_docs/version-2.0.0-beta-1/circuits-api/epoch-key-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-2/circuits-api/base-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-2/circuits-api/circuits.md
  packages/docs/versioned_docs/version-2.0.0-beta-2/circuits-api/epoch-key-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/circuits-api/base-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/circuits-api/circuits.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/circuits-api/epoch-key-proof.md
  packages/docs/versioned_docs/version-2.0.0-beta-3/core-api/user-state.md
Labels: documentation, ready for review

#487 445 synchronization
  packages/core/src/Synchronizer.ts
Labels: enhancement, ready for review
